export const manifestsCatalog = [
  { manifestId: 'https://files.tetras-libre.fr/dev/sun-400x400.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/test-vertical-video.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Heterogeneous-media-on-several-canvases.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Clock/manifestWithAnnotationTemplates_MAE.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/Clock/manifest.json' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0074-multiple-language-captions/manifest.json' },
  { manifestId: 'https://iiif.harvardartmuseums.org/manifests/object/299843' },
  { manifestId: 'https://iiif.io/api/cookbook/recipe/0002-mvm-audio/manifest.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/vertical_video_with_annot.json' },
  { manifestId: 'https://coeso.tetras-libre.fr/data/coeso-deliverable/Manual_Network_Configuration.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/multicanva-video.json' },
  { manifestId: 'https://dzkimgs.l.u-tokyo.ac.jp/videos/iiif_in_japan_2017/manifest.json' },
  { manifestId: 'https://resource.arvest.app/6b665140d80c98444a02f142c1a8fcb42d201940/8000x6000-Pogacar.json' },
  { manifestId: 'https://files.tetras-libre.fr/dev/youtube_big_media.json' },
];
